### ISSUE TITLE
My version of Worm War

### ISSUE THREAD

**Issue by ghost** [f4rk/worm_war#1]
Hi,

I developed a version of worm war before Reborn came out. I later scraped it due to some technical limitations of the alpha tools. However, I did get a significant amount of work done. Here is my version of it: https://github.com/stephenfournier/wormwar

[gif demo](http://gfycat.com/TerribleInsignificantDuck)

Here's a playthrough of it: https://www.youtube.com/watch?v=03V6YEv_C8I

Feel free to use my code. I haven't touched the project for many months, and I'm on a long break from Dota modding. If you use a significant amount of it, please [add me](http://steamcommunity.com/id/Myll/) as a contributor to worm war's workshop page.

Thank you and good luck!

**Comment by f4rk** [comment]
Hi Stephen,

Thanks for the message, your version of worm war looks very well done.

A lot of the major features of the game are complete but a lot of the polishing and effects (over head text, kill messages etc.) still needs to be figured out. I am new to making custom games and was trying to do everything myself to learn the tools. That being said, I think your code will be a good reference and very helpful. l will definitely add you to the contributors if any of your code is used.

Cheers,
Mark
